# Generated by Django 5.1.1 on 2025-03-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("collector_number", models.IntegerField()),
                (
                    "foil",
                    models.CharField(
                        choices=[("normal", "Normal"), ("foil", "Foil")], max_length=10
                    ),
                ),
                ("rarity", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=1)),
                ("scryfall_id", models.CharField(max_length=36, unique=True)),
                (
                    "purchase_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("condition", models.CharField(default="near_mint", max_length=20)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="mtg_app.set",
                    ),
                ),
            ],
        ),
    ]
