# Generated by Django 5.2.8 on 2025-11-13 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.CharField(max_length=100, unique=True, verbose_name='Scryfall ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('collector_number', models.CharField(max_length=20, verbose_name='Коллекционный номер')),
                ('foil', models.BooleanField(default=False, verbose_name='Фоил')),
                ('rarity', models.CharField(max_length=50, verbose_name='Редкость')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена покупки')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('condition', models.CharField(max_length=50, verbose_name='Состояние')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на изображение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.set', verbose_name='Сет')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название колоды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg_app.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg_app.deck')),
            ],
            options={
                'verbose_name': 'Карта в колоде',
                'verbose_name_plural': 'Карты в колодах',
                'unique_together': {('deck', 'card')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='mtg_app.DeckCard', to='mtg_app.card'),
        ),
    ]
