# Generated by Django 5.1.1 on 2025-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
