# Generated by Django 4.2.26 on 2025-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рыночная цена'),
        ),
    ]
