# Generated by Django 5.1.1 on 2025-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_app", "0002_alter_set_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название колоды")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("cards", models.ManyToManyField(to="mtg_app.card", verbose_name="Карты в колоде")),
            ],
        ),
    ]
