# Generated by Django 4.2.26 on 2025-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0002_card_market_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='market_price_currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта рынка'),
        ),
        migrations.AddField(
            model_name='card',
            name='purchase_price_currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта покупки'),
        ),
    ]
