# Generated by Django 5.1.1 on 2025-03-22 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_app", "0005_card_owner_deck_owner_alter_card_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="deck",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
