# Generated by Django 5.1.1 on 2025-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mtg_app", "0006_deck_created_at_deck_is_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="set",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="card",
            name="image_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Ссылка на изображение"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="deck",
            name="cards",
            field=models.ManyToManyField(
                blank=True, to="mtg_app.card", verbose_name="Карты в колоде"
            ),
        ),
        migrations.AlterField(
            model_name="deck",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
